### ISSUE TITLE
apt failure

### ISSUE THREAD

**Issue by gbaudot** [jubunel/proxysql#7]
Hello.
Trying your role, I get an error at package installation if I keep default value for proxysql_apt_version (2.0.*). Error message is:
`version number inconsistent with state=latest: proxysql=2.0.*`

This can easily be worked around with specifying a version number (without wildcard), and setting state present instead of present in task file solves the issue as well, but both options lack the ability to get package up to date...

Could not tell for sure, but maybe this should be considered an ansible apt module bug...

Regards,
GB

**Comment by michaeldg** [comment]
Which operating system and ansible version are you running? 

I have committed the change you mention:
```
 - name: Install, upgrade or downgrade ProxySQL
    apt:
      name: "proxysql={{ proxysql_apt_version }}"
      state: "{{ 'latest' if proxysql_apt_version[-1] == '*' else 'present' }}"
      force: yes # Allow downgrades
```
I have successfully ran this in ansible 2.6.2.

**Comment by gbaudot** [comment]
Hello.

Sorry for the lack of information:
  - OS: Debian 10 (buster)
  - ansible version: 2.9 (2.9.6-1ppa~trusty)

Again, not a big matter as setting a specific version solves it, but would you consider this deserves a fix, I guess it would look like this, with an empty string as default:

```
 - name: Install, upgrade or downgrade ProxySQL
    apt:
      name: "proxysql={{ ('=' + proxysql_apt_version) if proxysql_apt_version|length > 0 }}"
      state: "{{ 'latest' if proxysql_apt_version|length == 0 else 'present' }}"
      force: yes # Allow downgrades
```

Thanks for caring and regards,
GB
